/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: moxstudios (https://sketchfab.com/moxstudios)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/stitch-free-777e1bbc9df74359ad460c318d453072
title: Stitch Free
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/stitch.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.stitch_shading} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.stitch_shading} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.stitch_shading} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.stitch_shading} />
      </group>
    </group>
  )
}

useGLTF.preload('/stitch.gltf')
